name: C/C++ CI on ubuntu

on:
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#     - name: configure
#       run: ./configure
    - name: make
      run: |
       sudo add-apt-repository main
       sudo add-apt-repository universe
       sudo add-apt-repository restricted
       sudo add-apt-repository multiverse
       sudo apt-get update
       sudo apt-get install -y nettle
       make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
